#!/bin/bash

# if mount exit, simply call gvim:
mountpoint -q ~/tmp/cache1 && vim -f ~/tmp/cache1/notes.txt && 	exit 0

#echo "please mount using note-mount" ; exit 0

# Otherwise, create trcypt device, mount, edit/umount:
[[ ! -e /dev/mapper/cache1 ]] && sudo cryptsetup --type tcrypt open ~assaf/Dropbox/Apps/EDS/cache1 cache1
mkdir -p /home/assaf/tmp/cache1
sudo mount -o uid=assaf0,gid=users /dev/mapper/cache1 /home/assaf/tmp/cache1/
vim /home/assaf/tmp/cache1/notes.txt
sudo umount /home/assaf/tmp/cache1 && sudo cryptsetup close cache1

