#! /bin/bash

case "$1" in 
"") 
  echo "Usage: ${0##*/} {inernal-only | external-right-only | external-normal-only}"
  ;;
internal-only)
  xrandr --output eDP1 --auto --output HDMI1 --off
  ;;
external-normal-only)
  xrandr --output eDP1 --off  --output HDMI1 --auto --rotate normal 
  ;;
external-right-only)
  xrandr --output eDP1 --off  --output HDMI1 --auto --rotate right
  ;;
*)
  echo "Parameter value $1 is not supported"
  echo "Usage: ${0##*/} {inernal-only | external-right-only}"
  ;;
esac


