#!/bin/bash

export VSLICKALIAS=~/scripts/se.aliases.als:aliases.als
#export LM_LICENSE_FILE=9050@ls-csi;
export TMP=`pwd`;
export wspath=`pwd`;

if [ "$OSTYPE" = "linux-gnu" ]; then
VS="/opt/slickedit/bin"
else 
VS="/"
fi

#echo "$VS/vs +new $1"

$VS/vs +new -sul $1



