#!/bin/sh
mkdir -p $HOME/var/log
nohup wingo --replace -p 1 --log-level 3 > $HOME/var/log/wingo.log 2>&1 & 
sleep 4
#wingo-settings
xrdb -merge ~/.Xresources
xbindkeys 

# disable screen blank
xset s off -dpms

kbd_home.sh workman

TERM=linux-assaf tmuxinator misc 

nohup clipit & 
nohup autokey &
