#!/bin/sh

set -x

mkdir -p $HOME/var/log
nohup wingo --replace -p 1 --log-level 3 > $HOME/var/log/wingo.log 2>&1 & 
sleep 4
#wingo-settings
# xrdb -merge ~/.Xresources
# xbindkeys 

# clipit &  

# disable screen blank
xset s off -dpms

kbd_home.sh workman


sxhkd & 
lemonade server &


# The file ~/hostname.txt is not part of git env (spcific for every machine)
case "`cat ~/hostname.txt`" in
    'hlinux')
        TERM=linux-assafb tmuxinator hlinux
        wingo-cmd 'RenameWorkspace "1" "hlinux"' 
        ;;
    'wlinux' )
        TERM=linux-assafb tmuxinator laptop
        wingo-cmd 'RenameWorkspace 1 "laptop"' 
        wingo-cmd 'RenameWorkspace 2 "code"' 
        wingo-cmd 'DeleteWorkspace 3' 
        wingo-cmd 'RenameWorkspace 4' 
        ;;
    * )
        ;;
esac
