#!/bin/sh
wingo --replace -p 1 --log-level 3 > $HOME/wingo.log 2>&1 & 
sleep 4
#wingo-settings
xrdb -merge ~/.Xresources
xbindkeys 
kbd_home.sh
tmuxinator misc 
#for i in {1..7}
#do
#	xfce4-terminal -e 'ssh assafb@dev64-build12'
#done
# xfce4-terminal -e "tmux attach-session -t misc"  &
#tmux attach-session -t misc"
